### ISSUE TITLE
Ray to Circle collision broken

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#30]
c2CircletoRay collision seems to be always broken.
My c2Ray & c2Circle:
```c++
c2Ray ray;
ray.p = c2V(100, 100);
ray.d = c2V(100, 100);
ray.t = 1;

c2Circle circle;
circle.r = 30;
circle.p = c2V(200, 200);
```
I get the impact with:
```c++
c2Raycast cast;
if (c2RaytoCircle(ray, circle, &cast)) {
        c2v impact = c2Impact(ray, cast.t);
}
```

The resulting impact is { 147.852, 147.852 }, which is outside the circle. In each case(circle position) I tested the resulting impact is always outside the circle.

**Comment by RandyGaul** [comment]
Thanks taking a look now !

**Comment by RandyGaul** [comment]
Here's the rendering of your code:

![image](https://user-images.githubusercontent.com/1919825/27276126-05c744ea-548f-11e7-8a19-b15faf60392e.png)

All is working as intended! Except I bet you meant to normalize your ray direction :)

Try:

    ray.d = c2Norm(c2V(100, 100));

Here's the code I used to do the rendering in the tinyc2 example demo:

	void sro5hRayBug( )
	{
		c2Ray ray;
		ray.p = c2V( 100.0f, 100.0f );
		ray.d = c2V( 100.0f, 100.0f );
		ray.t = 1.0f;

		c2Circle circle;
		circle.r = 30.0f;
		circle.p = c2V( 200.0f, 200.0f );

		DrawCircle( circle.p, circle.r );

		c2Raycast cast;
		if ( c2RaytoCircle( ray, circle, &cast ) )
		{
			c2v impact = c2Impact( ray, ray.t );
			c2v end = c2Add( impact, c2Mulvs( cast.n, 1.0f ) );
			tgLineColor( ctx, 1.0f, 0.2f, 0.4f );
			tgLine( ctx, impact.x, impact.y, 0, end.x, end.y, 0 );
		}

		c2v end = c2Add( ray.p, c2Mulvs( ray.d, ray.t ) );
		tgLineColor( ctx, 1.0f, 1.0f, 1.0f );
		tgLine( ctx, ray.p.x, ray.p.y, 0, end.x, end.y, 0 );
	}

**Comment by sro5h** [comment]
In your function `sro5hRayBug` you don't seem to normalize `ray.d`, is that a typo?

**Comment by RandyGaul** [comment]
The ray does not have to be normalized, but it seemed like you wanted it to be judging by your post. Here's a pretty good link on vectors and normalization, take a peek if any of the math here is confusing. Rays are just vectors for the most part :)

https://www.khanacademy.org/computing/computer-programming/programming-natural-simulations/programming-vectors/a/vector-magnitude-normalization

**Comment by sro5h** [comment]
Well I feel like I understand the math (normalization creates a Vector of length 1 with the same direction) :)
But I really don't understand why my code gives me the wrong impact point.

**Comment by sro5h** [comment]
Why are you using `ray.t` in `c2Impact`, wouldn't that just give you the endpoint of the ray rather than the actual impact?

**Comment by sro5h** [comment]
What really confuses me is that if I take the code from this issues and replace the circle with an AABB the raycast gives me the correct impact. So there has to be some difference between `c2RaytoCircle` and `c2RaytoAABB` if one time `cast.t` is correct even if `ray.d` is not normalized and the other time it isn't

**Comment by RandyGaul** [comment]
The impact point is off because the function `c2RaytoCircle` is yet again written with speed in mind. It's not really your fault, it's just confusing. Most other libraries will take extra care and effort to prevent this kind of thing from happening, but tinyc2 is much more "bare metal".

![ray](https://user-images.githubusercontent.com/1919825/27278852-75ff44f8-5497-11e7-82a4-b7c01a8612e6.gif)

If we look here we can see a huge floating point value. It doesn't even have decimal points. That's because the function is taking big vectors and dotting them together, making a giant value. This giant value has such poor precision that the t value, calculated later, is visibly inaccurate. This is because large floating point numbers have very low precision.

To prevent this kind of thing from happening normalizing the Ray's direction vector results in a much smaller `disc` value, of only 900.003906. That is plenty small enough to give an accurate result.

**Comment by sro5h** [comment]
Ok thanks now I understand it, thanks for the help. Maybe a notice along the lines of "Keep in mind that direction vectors with a huge length can introduce major inaccuracy in the result. As a fix it is best to normalize the direction of the ray" in a comment above the function would be helpful for others?

**Comment by RandyGaul** [comment]
Sure I'll add in a big fat comment right above the definition of c2Ray. Good idea!
