### ISSUE TITLE
tinytime (windows) elapsed time as negative value

### ISSUE THREAD

**Issue by FredrickV** [RandyGaul/tinyheaders#40]
Is this by design?, in function int64_t ttElapsed(), i changed the return to:

`return (int64_t)(now.QuadPart - timer->prev.QuadPart);`

**Comment by zao** [comment]
For reference, it currently https://github.com/RandyGaul/tinyheaders/blob/3bfa803/tinytime.h#L104 is `return (int64_t)(timer->prev.QuadPart - now.QuadPart);`

**Comment by RandyGaul** [comment]
Yeah I think this was a bug someone else fixed recently. Thanks for bringing it up!

**Comment by FredrickV** [comment]
I don't know what that means, it's been there since initial commit, and is still there.

**Comment by zao** [comment]
Sorry, my comment was to point out where in the source it was currently incorrect, not to imply that it was fixed in some way.

**Comment by RandyGaul** [comment]
Oh whoops. I misunderstood. I somehow thought you were referring to: https://github.com/RandyGaul/tinyheaders/issues/28

I see what you meant now! That's not by design; that's an oversight that somehow slipped in here. It's actually not on my local machine. Thanks for following up. Looks like the now and prev need to be swapped.
