### ISSUE TITLE
Why is there a complete copy of "The Adventures of Sherlock Holmes" in the TinyDeflate folder?

### ISSUE THREAD

**Issue by bumblebritches57** [RandyGaul/tinyheaders#58]
feldspar.txt is no shit, a whole god damn book...

what the shit

**Comment by RandyGaul** [comment]
lmao, well I believe I was compressing the book to test tinydeflate’s custom written dynamic tree compressor.

I’m a little surprised I checked in an entire book... Was the size of the book annoying when you cloned the repo? If it’s not bothering anyone I suppose I’ll leave it there; it is a really nice text to test out compression and decompression functions.

Plus I found it online for free :)

But if it’s troublesome due to file size I can remove it!

**Comment by bumblebritches57** [comment]
I mean kinda, it's over 10% of the entire repos size.

I actually deleted the bare repo and redid it with --depth 1 to try to reduce the size, and it only came down from 12 to 10mbs, that's why I went lookin around lol.

**Comment by RandyGaul** [comment]
Oh I see, you must be looking for reference to work on your stuff: https://github.com/bumblebritches57/ModernPNG

:)

Anyways, closing this for now. Feel free to comment more here if you like.

**Comment by bumblebritches57** [comment]
Yup, I've read the RFC about half a dozen times, but it's still not clicking, and code is much easier to learn from for me. :)

**Comment by RandyGaul** [comment]
Well feel free to ask question if you get any
