### ISSUE TITLE
mingw support

### ISSUE THREAD

**Issue by codz01** [RandyGaul/tinyheaders#78]
Hi
i tried to compile tinysound example (sdl one)  , but tons of errors appears ! 
does mingw considered as supported compiler for this library ?

**Comment by RandyGaul** [comment]
Hi there, I just made a quick fix for the compile errors. I'm using tdm-gcc as my mingw compiler. Unfortunately the dll and lib combo I have in the repo is not compatible with tdm-gcc. So users will have to provide their own installation of SDL.

The compile errors in question were improper use of `selectany`. Typically `selectany` is needed for placing global variables into an "inline-only" header. It is not necessary for tinysound since all the globals were SIMD constants only needed for the .c implementation portion.

Hope this helps!

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/baa64a5e41e818b1566b26f16465884d74182ee2

**Comment by codz01** [comment]
Hi 
i am also using tdm-gcc (4.9) , i re-tried with your last git commit , but still alot of errors ( all about : crosses initialization of ... )  
![error](https://user-images.githubusercontent.com/10813427/36156042-3e8692c8-10d6-11e8-9631-616f121ac154.png)

**Comment by RandyGaul** [comment]
I believe you need to use `-fpermissive`. Here was my command line (from the Makefile): `g++ -I. $(OBJS) -w -lSDL2 -o $(OBJ_NAME) -fpermissive`

**Comment by codz01** [comment]
i just type "make" , you can see the screenshot (first line in the command prompt) , -fpermissive is there  , its in the makefile .

BTW , i am using mingw 32bits

**Comment by RandyGaul** [comment]
Ah. I have 64 bit compiler. I can try to take a look later tonight after work! If possible, I recommend using MSCV instead (it's free!) for now.

**Comment by codz01** [comment]
ok now i make it working but after removing the immediate initialization of some variables , e.g 
( int byte_to_write = samples_to_write * ctx->bps; ) **becomes**
(int byte_to_write;   byte_to_write =  samples_to_write * ctx->bps; )

**Comment by RandyGaul** [comment]
I could never quite figure out how to get a repro on those errors. If you end up with a working solution (sounds like you did) please put up a pull request. Closing for now, but feel free to re-open or add comments if you like.
