### ISSUE TITLE
spritebatch demo leaks rapidly

### ISSUE THREAD

**Issue by meshula** [RandyGaul/tinyheaders#86]
All the spritebatch demo scenes use a lot of memory, however, Scene2 in particular leaks about 100 mb a second at at a constant rate until certain doom... I haven't taken the time to figure out what's going on, but I thought I'd bring it to your attention.

**Comment by RandyGaul** [comment]
That's interesting! Thanks for noting this. I'll take a look likely this weekend :) Please let me know if you peak any further and find where the culprit allocation comes from.

**Comment by RandyGaul** [comment]
Oh and did you happen to measure how much memory they are using? I have yet to focus specifically on auditing the memory usage, and instead have been focusing my energy on the API lately (and on releasing tinytiled.h so I can actually load tiles and draw them with the spritebatch API).

**Comment by RandyGaul** [comment]
Turns out I was missing this line: https://github.com/RandyGaul/tinyheaders/blob/master/tinyspritebatch.h#L1342

Did not detect any other leaks. Also I am worried that the scenes are using a lot of memory like you mentioned, so I performed an audit. As far as I can tell, they seem to just be using a few megabytes, as expected. This is the cost of storing textures in memory and making atlases and whatnot.

Taking a look here ( https://github.com/RandyGaul/tinyheaders/blob/master/tinyspritebatch.h#L679-L694 ) reveals hints about what memory is stored, and why. There is heap memory for various hash tables, an array of sprites, and an input buffer array.

Tweaking the initial size of hashtables can occur here: https://github.com/RandyGaul/tinyheaders/blob/master/tinyspritebatch.h#L756-L757

While tweaking the exact size of atlases, and atlas behavior can be done here: https://github.com/RandyGaul/tinyheaders/blob/master/tinyspritebatch.h#L191-L198

Closing for now, but if anyone wanted to re-open or comment here feel free to do so.

**Comment by RandyGaul** [comment]
Went ahead to record heap memory usage during the test scenes. Highest I could find was 222772 bytes, which is 0.222772 megabytes.

https://github.com/RandyGaul/tinyheaders/commit/d7bed97104bab74881fac20c121580167ed1d346

**Comment by meshula** [comment]
Great! I'll retest.

**Comment by meshula** [comment]
I can confirm that the atlas memory caps out around 230kb, and that the process memory caps out at 135mb in the demo. Thanks for the fix, looking forward to playing with the library!
