### ISSUE TITLE
Crash when parsing the following input file

### ISSUE THREAD

**Issue by ZenToad** [RandyGaul/tinyheaders#93]
case 8310322674355535532U: // tilesets
	{
		tinytiled_expect(m, '[');

		while (tinytiled_peak(m) != ']')
		{
			tinytiled_tileset_t* tileset = tinytiled_tileset(m);
1933:		tileset->next = m->map.tilesets; <<<<< VS debugging exception here (tileset is nullptr)
			m->map.tilesets = tileset;
			tinytiled_try(m, ',');
		}

		tinytiled_expect(m, ']');
	}	break;

[untitled.txt](https://github.com/RandyGaul/tinyheaders/files/1922310/untitled.txt)

**Comment by RandyGaul** [comment]
Thanks! Let me take a look real quick ...

**Comment by RandyGaul** [comment]
OK! Got fix here: https://github.com/RandyGaul/tinyheaders/commit/087f41a138820a51cb70d189c92cd9b14fa85825

Problem was that tinytiled didn't know how to handle the option of "do not embed tileset". This should be supported by tinytiled! I missed this case since it is unfortunately not documented in the official documentation: http://doc.mapeditor.org/en/stable/reference/json-map-format/

Thanks a lot for taking the time to post your map up! It was very helpful in finding and fixing the bug :)

Closing for now, feel free to re-open or comment if you like though.
